import Head from 'next/head'
import Image from 'next/image'
import Header from './Components/Header'

export default function Home() {
  return (
    <div className='h-screen w-screen- bg-orange-300'>
      <Head>
        <title>Web3 Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header />
    </div>
  )
}
